name: Deploy ke VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy ke VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 103.168.146.195
          username: eliaulia
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/eliaulia/UAS_WEB
            git pull origin main
            docker compose down
            docker compose pull
            docker compose up -d